let controlBtnArr = [
  "<span>Space</span>",
  "Backspace",
  "Tab",
  "Del",
  "CapsLock",
  "Enter",
  "Shift<span>Left</span>",
  "Shift<span>Right</span>",
  "Ctrl",
  "Win",
  "Alt<span>Left</span>",
  "Alt<span>Right</span>",
  "&#5130",
  "&#5121",
  "&#5123",
  "&#5125",
];
let en_alphabet = ["q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "a", "s", "d", "f", "g", "h", "j", "k", "l", "z", "x", "c", "v", "b", "n", "m"];
const en_num = ["`", 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, "-", "="];
const en_symb = ["~", "!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "+", "="];
const en_num_ext = ["[", "]", "\\", ";", "'", ",", ".", "/"];
const en_symb_ext = ["{", "}", "|", ":", '"', "<", ">", "?"];
let ru_alphabet = [
  "й",
  "ц",
  "у",
  "к",
  "е",
  "н",
  "г",
  "ш",
  "щ",
  "з",
  "ф",
  "ы",
  "в",
  "а",
  "п",
  "р",
  "о",
  "л",
  "д",
  "я",
  "ч",
  "с",
  "м",
  "и",
  "т",
  "ь",
  "х",
  "ъ",
  "\\",
  "ж",
  "э",
  "б",
];
const ru_num = ["ё", 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, "-", "="];
const ru_symb = ["Ё", "!", '"', "№", ";", "%", ":", "?", "*", "(", ")", "-", "="];
const ru_num_ext = ["ю", "."];
const ru_symb_ext = ["Ю", ","];
const dataAttribute = [
  "Backquote",
  "Digit1",
  "Digit2",
  "Digit3",
  "Digit4",
  "Digit5",
  "Digit6",
  "Digit7",
  "Digit8",
  "Digit9",
  "Digit0",
  "NumpadSubtract",
  "Equal",
  "KeyQ",
  "KeyW",
  "KeyE",
  "KeyR",
  "KeyT",
  "KeyY",
  "KeyU",
  "KeyI",
  "KeyO",
  "KeyP",
  "KeyA",
  "KeyS",
  "KeyD",
  "KeyF",
  "KeyG",
  "KeyH",
  "KeyJ",
  "KeyK",
  "KeyL",
  "KeyZ",
  "KeyX",
  "KeyC",
  "KeyV",
  "KeyB",
  "KeyN",
  "KeyM",
   "BracketLeft",
  "BracketRight",
    "Semicolon",
  "Quote",
  "Backslash",
    "NumpadDecimal",
  "Period",
  "Slash",
];
export default {
  controlBtnArr,
  en_symb,
  en_num_ext,
  en_alphabet,
  en_symb_ext,
  ru_alphabet,
  en_num,
  ru_num,
  ru_symb,
  ru_num_ext,
  ru_symb_ext,
  dataAttribute,
};
